api:
  prefix: /api
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
    active: "qa"


build:
  version: "3.0"

account:
  message: "Welcome to Bank account related local APIs "
  contactDetails:
    name: "Trung hiep - Developer"
    email: "phamtrunghiep1201@gmail.com"
  onCallSupport:
    - 0991234567
    - 0991234569