api:
  prefix: "/api"

server:
  port: 8090

spring:
  application:
    name: "loan"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:loandb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

# Config Actuator & Shutdown
management:
  endpoints:
    shutdown:
      enabled: true
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# Config Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

# Thông tin hiển thị lên Dashboard Eureka / Actuator Info Endpoint
info:
  app:
    name: "loan"
    version: "1.0.0"
    description: "loan Service"