services:
  account:
    image: "phamhiep1/account:v1"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

  loan:
    image: "phamhiep1/loan:v1"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

  card:
    image: "phamhiep1/card:v1"
    container_name: card-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

networks:
  bank:
    driver: "bridge"